apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

namespace: apps-prod
nameSuffix: -prod

commonLabels:
  environment: prod

images:
  - name: ghcr.io/example-org/sample-api
    newTag: prod-2026.03

patches:
  - path: replicas.yaml
  - path: configmap.yaml
  - path: ingress.yaml
