apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root-stage-us-east-1
  namespace: argocd
spec:
  project: platform
  source:
    repoURL: https://github.com/your-org/your-gitops-repo.git
    targetRevision: main
    path: argocd/bootstrap
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
