apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sample-worker
  namespace: argocd
spec:
  project: apps
  source:
    repoURL: https://github.com/your-org/your-gitops-repo.git
    targetRevision: main
    path: apps/sample-worker/overlays/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: apps-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
